version: '3.8'
services:
  server:
    build: ./server
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=ShoppingCartDb;User Id=sa;Password=Your_password123;Encrypt=False;TrustServerCertificate=True
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - db

  client:
    build: ./client
    ports:
      - "5000:80"

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123   # 👈 strong password required!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
