version: '3.8'
services:
  server:
    build: ./server
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  client:
    build: ./client
    ports:
      - "5000:80"
